### ISSUE TITLE
Text ids in non TextIDs.lua files

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar-utils#15]
@teschnei we either need to 1) split IDs.lua into TextIDs and *not*TextIDs, or 2) mass rename all the TextIDs.lua files and requires to match the IDs.lua you used for instance zones, or 3) rename the IDs.lua to TextIDs.lua, or 4) modify the java here in the utils and then rebuild it so it stops completely missing them. I can do either of the first 3 of those 4. Sorry but not a java dude not setting up a build environment for it. 

Options 2 and 3 might have probs since you have things other than text id's in the instance zone ones - probably a bunch of fixme marks on your mob ids.. 

I recall @starlightknight had warned us about this back when you did those files for instancing, and last I knew he wasn't in the ffxi scene anymore since he couldn't get a client working under linux.

So how do we handle this?

**Comment by teschnei** [comment]
there's not too many instances yet so option 1 is not going to be that hard (only like 3 assaults that would need fixing)

**Comment by teschnei** [comment]
then I guess we can put mobids and npcids into... entityIDs? something, doesn't really matter what, and then I think the tool will just pick them up anyways (it just searches for things that look like IDs for mobs/npcs, IIRC).

**Comment by TeoTwawki** [comment]
the one that finds npc id's searches all over, the textID one only hits the zone\TextIDs.lua

so IDs.lua to TextIDs & EntityIDs it is, I'll get on that soon and then close this.

**Comment by teschnei** [comment]
Yep, that's what I meant. Sounds good then

**Comment by TeoTwawki** [comment]
if https://github.com/DarkstarProject/darkstar/pull/5157 merges we have to go option 4, updating the tool to read files other than textids.lua
